config/routes.rb
 Rails.application.routes.draw do
 

  
  

  get "/"=> "index#accueil"
  get "/accueil"=> "index#accueil"
  
  
  

  get "/contact"=> "index#contact"
  get "/photos"=> "index#photos"
  post "/contact" => "index#envoi_message"
  
  get "/show" => "index#show_messages"
  get "/effacer/:id" =>"index#effacer_messages"
  get "/modifier/:id" =>"index#modifier_messages"
  post "/update/:id" =>"index#update_messages"
  
  
  resources :dates
  
 
end

  
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/evenement.rb
class Evenement < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
end

app/controllers/dates_controller.rb
class DatesController < ApplicationController
    


def new



end

def destroy

@evenement=Evenement.find(params[:id])
@evenement.destroy
redirect_to dates_path

end

def create
	
	@evenement=Evenement.new(evenement_params)
	@evenement.save
	redirect_to dates_path

end

def index

	@evenements=Evenement.all

end


private

	def evenement_params
		
		params.require(:evenement).permit(:nom,:date_texte, :lien, :ladate,:afficher)
	end

end

app/controllers/index_controller.rb
class IndexController < ApplicationController
    
   def accueil
   	
   	@prochaines_dates=Evenement.all

	end

	def photos
	@prochaines_dates=Evenement.all
	end

	def show_messages
	@prochaines_dates=Evenement.all
	@message=Message.all
	end
	
	def effacer_messages
	@message=Message.find(params[:id])
	@message.destroy
	redirect_to show_path
	
	end


	def contact

	@prochaines_dates=Evenement.all
	end
	
	def envoi_message
		
		@message=Message.new(msg_params)
		@message.save
		redirect_to show_path
	
	end
	
	

	
private

	def msg_params
		
		params.require(:msg).permit(:nom,:prenom, :message, :mail)
	end
	
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dates_helper.rb
module DatesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/dates/index.html.erb
<div class=container>




      <div class="row">

           <div class="col-md-8"  >  
           
           <h1> il y a <%=@evenements.count%> évènements dans la base</h1>
               <%  @evenements.each do |f|  %>  
                   <p></p>
                   ---------------------------
                   <p> Intitulé :  <%= f.nom %>  </p>
                   <p> Date en français : <%= f.date_texte %></p>
                   <p> Lien web : <%= f.lien %></p>
                   <p> date de début : <%= f.ladate %></p>
                    <p>Evènement actif ?  : <%= f.afficher %></p>
                    <p>  <%=link_to "Effacer", date_path(f),:method => :delete%></p>
            
               <% end %>
           </div>
            
           

      </div>


    

</div>

app/views/dates/new.html.erb
 <div class=container>




      <div class="row">

           <div class="col-md-8"  >  
 
 <div class="formulaire_contact">
          
              <form  action="/dates" method="POST">   
          
              
              
              <div class="form-group row">
                <label for="nom-input" class="col-2 col-form-label">Titre</label>
                <div class="col-10">
                  <input class="form-control" type="text" placeholder="Au Boui-Boui" id="nom-input"  name="evenement[nom]">
                </div>
              </div>
              
              <div class="form-group row">
                <label for="date_text-input" class="col-2 col-form-label">Quand?</label>
                <div class="col-10">
                  <input class="form-control" type="text" placeholder="tous les weeks-end" id="date_text-input"  name="evenement[date_texte]">
                </div>
              </div>
              
              <div class="form-group row">
                <label for="lien_web-input" class="col-2 col-form-label">Lien web pour la réservation</label>
                <div class="col-10">
                  <input class="form-control" type="text" placeholder="lien_web" id="example-url-input" name="evenement[lien]">
                </div>
              </div>
              
               <div class="form-group row">
              <label for="date-input" class="col-2 col-form-label">date évènement</label>
              <div class="col-10">
                <input class="form-control" type="date" placeholder="date de début" id="date-input"  name="evenement[ladate]">
              </div>
            </div>
            
            <div class="form-group row">
              <label for="afficher-input" class="col-2 form-check-label">Evènement actif ?</label>
              <div class="col-10">
                <input class="form-control" type="checkbox"  id="afficher-input"  name="evenement[afficher]">
              </div>
            </div>
            
            
       
             
              <button type="submit" class="btn btn-primary">Envoyer</button>
              
            </form>     
          
  </div>
  
   </div>
  
   </div>
  
   </div>
  
  

app/views/index/_accueil_contenu.html.erb
 <div class="contenu">

                  <div class="sous-contenu">
                      <p class ="titre-contenu">  Actuellement à Lyon toute la semaine, au café théatre le Boui-Boui !</p>
                      <img id="img_spectacle" src= <%= image_path("accueil/affiche.jpg") %> alt="affiche"/>
                      
                  </div>

                  <div class="sous-contenu">
                      <p class ="titre-contenu">  Telerama en parle !</p>
                       <a href="http://sortir.telerama.fr/evenements/spectacles/clemence-de-villeneuve,210184.php"><img id="img-spectacle" src=<%= image_path("accueil/telerama.jpg") %> alt="article"/></a>
                  </div>


                   <div class="sous-contenu">
                     <p class="titre-contenu"> Teaser du spectacle</p>
                    
                      </div>
                   </div>

   </div>

app/views/index/_contact_contenu.html.erb
 
        <div class="formulaire_contact">
          
              <form action="/contact" method="POST">   
          
              
              
              <div class="form-group row">
                <label for="nom-input" class="col-2 col-form-label">Nom</label>
                <div class="col-10">
                  <input class="form-control" type="text" placeholder="Dupont" id="nom-input"  name="msg[nom]">
                </div>
              </div>
              
              <div class="form-group row">
                <label for="prenom-input" class="col-2 col-form-label">Prénom</label>
                <div class="col-10">
                  <input class="form-control" type="text" placeholder="Jean" id="prenom-input"  name="msg[prenom]">
                </div>
              </div>
              
              <div class="form-group row">
                <label for="msg-input" class="col-2 col-form-label">Message</label>
                <div class="col-10">
                  <input class="form-control" type="text" placeholder="Mon Message" id="example-url-input" name="msg[message]">
                </div>
              </div>
              
               <div class="form-group row">
              <label for="mail-input" class="col-2 col-form-label">Mail</label>
              <div class="col-10">
                <input class="form-control" type="email" placeholder="jeandupont@example.com" id="email-input"  name="msg[mail]">
              </div>
            </div>
            
            
       
             
              <button type="submit" class="btn btn-primary">Envoyer</button>
              
            </form>     
          
  </div>

app/views/index/_envoi_message_contenu.html.erb
 
     <div class="formulaire_contact">
       
       <h1>
            Merci pour le message <%=@message.prenom%>, <%=@message.nom%>
           
       </h1>
       <p> Nous vous répondrons à cette adresse <%=@message.mail%></p>
       
     </div> 

app/views/index/_modifier_contenu.html.erb
 
        <div class="formulaire_contact">
          
              <form action="/update/<%=@message.id%>" method="POST">   
          
              
              
              <div class="form-group row">
                <label for="nom-input" class="col-2 col-form-label">Nom</label>
                <div class="col-10">
                  <input class="form-control" type="text" placeholder=<%=@message.nom%> id="nom-input"  name="msg[nom]">
                </div>
              </div>
              
              <div class="form-group row">
                <label for="prenom-input" class="col-2 col-form-label">Prénom</label>
                <div class="col-10">
                  <input class="form-control" type="text" placeholder=<%=@message.prenom%> id="prenom-input"  name="msg[prenom]">
                </div>
              </div>
              
              <div class="form-group row">
                <label for="msg-input" class="col-2 col-form-label">Message</label>
                <div class="col-10">
                  <input class="form-control" type="text" placeholder=<%=@message.message%> id="example-url-input" name="msg[message]">
                </div>
              </div>
              
               <div class="form-group row">
              <label for="mail-input" class="col-2 col-form-label">Mail</label>
              <div class="col-10">
                <input class="form-control" type="email" placeholder=<%=@message.mail%> id="email-input"  name="msg[mail]">
              </div>
            </div>
            
            
       
             
              <button type="submit" class="btn btn-primary">Envoyer</button>
              
            </form>     
          
  </div>

app/views/index/_photos_contenu.html.erb
<div id="galleries_photos">

<h1>Photos du spectacle</h1>
 <!-- portfolio section -->

      <div class="photos">

        <ul >

        <div class="row">

            <li class="col-lg-3 col-md-3 col-sm-4 col-xs-6">
                <img class="img-responsive" src=<%= image_path("gallerie/1.jpg") %> >
            </li>
            <li class="col-lg-3 col-md-3 col-sm-4 col-xs-6">
                <img class="img-responsive" src=<%= image_path("gallerie/2.jpg") %> >
            </li>
            <li class="col-lg-3 col-md-3 col-sm-4 col-xs-6">
                 <img class="img-responsive" src=<%= image_path("gallerie/3.jpg") %> >
            </li>
            <li class="col-lg-3 col-md-3 col-sm-4 col-xs-6">
                 <img class="img-responsive" src=<%= image_path("gallerie/4.jpg") %> >
            </li>
            <li class="col-lg-3 col-md-3 col-sm-4 col-xs-6">
                <img class="img-responsive" src=<%= image_path("gallerie/5.jpg") %> >
            </li>
         </div>








          </ul>
    </div>


</div>



    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-body">
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div>

app/views/index/_reseaux_sociaux_haut.html.erb
<div id="reseaux_sociaux_haut">

              <a href="https://www.youtube.com/watch?v=eGrW0u0C_FIhttps://www.youtube.com/watch?v=eGrW0u0C_FI" target="_blank"> <i class="fa fa-youtube-square" aria-hidden="true"></i></a>
            <a href="https://www.facebook.com/people/Cl%C3%A9mence-de-Villeneuve/519459672" target="_blank"><i class="fa fa-facebook-square" aria-hidden="true"></i></a>
            <a href="https://www.instagram.com/clemencedevilleneuve/" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a>
</div>

app/views/index/accueil.html.erb
 
<div class=container>

     <div id="barremenu">

          <div class="row">
              <div class="col-md-8">
                   <ul class="nav nav-pills nav-justified ">
                      <li role="presentation"  class="active"> <%= link_to 'Accueil', :controller=>'index', :action=>'accueil' %></li>
                      <li role="presentation" > <%= link_to 'Photos', photos_path %></li>
                      <li role="presentation"> <%= link_to "M'écrire", :controller=>'index', :action=>'contact' %></li>
                  </ul>
              </div>

              <div class="col-md-4">
                <%= render "shared/reseaux_sociaux_haut" %>                
              </div>
         </div>

    </div>


        <div class="row">
            <div class="col-md-12">
                 <div  class="page-header" >
                        <h1>Bienvenue sur mon site,</h1>
                        <p>
                        <h1> N'hésitez pas à me laissez des messages !</h1>
                  </div>
            </div>
        </div>

    
       <div class="row">

        <div class="modal fade" id="youtubeModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-body">
              <div id="videoModalContainer">

              </div>
            </div>
            <div class="modal-footer">
              <button id="CloseModalButton" type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
            </div>
          </div>
        </div>
      </div>

           <div class="col-md-8"  >
            
              <%=render "index/accueil_contenu" %>
            
           </div>
            
           <div class="col-md-4"  >  
               <%=render "shared/menu_fixe_droit" %>
          </div>     

      </div>
</div>

      <%=render "shared/footer" %>





<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
      <script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>

      <!-- Loading Images for faster page load based on : START Fast & Agile YouTube Embed by Schoberg.net -->
      <script src="JS/YouTubeDefaultImageLoader.js"></script>



      <!--<script src="js/iframe_Api_VideoLoader.js"></script>-->
      <!-- Include all compiled plugins (below), or include individual files as needed -->
      <script src="http://netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

app/views/index/contact.html.erb
<div class=container>

 <div id="barremenu">

      <div class="row">
            <div class="col-md-8">
                           <ul class="nav nav-pills nav-justified ">
                         <li role="presentation"> <%= link_to 'Accueil', :controller=>'index', :action=>'accueil' %></li>
                          <li role="presentation"  > <%= link_to 'Photos', :controller=>'index', :action=>'photos' %></li>
                          <li role="presentation" class="active"> <%= link_to "M'écrire", :controller=>'index', :action=>'contact' %></li>
                          </ul>
            </div>

            <div class="col-md-4">
              <%= render "shared/reseaux_sociaux_haut" %>                
            </div>

     </div>
</div>


      <div class="row">

           <div class="col-md-8"  >                      
               <%=render "index/contact_contenu" %>                     
           </div>
            
           <div class="col-md-4"  >  
               <%=render "shared/menu_fixe_droit" %>
          </div>     

      </div>


    

</div>


  <%=render "shared/footer" %>

app/views/index/envoi_message.html.erb
<div class=container>

 <div id="barremenu">

      <div class="row">
            <div class="col-md-8">
                           <ul class="nav nav-pills nav-justified ">
                         <li role="presentation"> <%= link_to 'Accueil', :controller=>'index', :action=>'accueil' %></li>
                          <li role="presentation"  > <%= link_to 'Photos', :controller=>'index', :action=>'photos' %></li>
                          <li role="presentation" class="active"> <%= link_to "M'écrire", :controller=>'index', :action=>'contact' %></li>
                          </ul>
            </div>

            <div class="col-md-4">
              <%= render "shared/reseaux_sociaux_haut" %>                
            </div>

     </div>
</div>


      <div class="row">

           <div class="col-md-8"  >                      
               <%=render "index/envoi_message_contenu" %>                     
           </div>
            
           <div class="col-md-4"  >  
               <%=render "shared/menu_fixe_droit" %>
          </div>     

      </div>


    

</div>


  <%=render "shared/footer" %>

app/views/index/modifier_messages.html.erb
<div class=container>

 <div id="barremenu">

      <div class="row">
            <div class="col-md-8">
                           <ul class="nav nav-pills nav-justified ">
                         <li role="presentation"> <%= link_to 'Accueil', :controller=>'index', :action=>'accueil' %></li>
                          <li role="presentation"  > <%= link_to 'Photos', :controller=>'index', :action=>'photos' %></li>
                          <li role="presentation" class="active"> <%= link_to "M'écrire", :controller=>'index', :action=>'contact' %></li>
                          </ul>
            </div>

            <div class="col-md-4">
              <%= render "shared/reseaux_sociaux_haut" %>                
            </div>

     </div>
</div>


      <div class="row">

           <div class="col-md-8"  >                      
               <%=render "index/modifier_contenu" %>                     
           </div>
            
           <div class="col-md-4"  >  
               <%=render "shared/menu_fixe_droit" %>
          </div>     

      </div>


    

</div>


  <%=render "shared/footer" %>

app/views/index/photos.html.erb
<div class=container>

 <div id="barremenu">

      <div class="row">
            <div class="col-md-8">
                           <ul class="nav nav-pills nav-justified ">
                         <li role="presentation"> <%= link_to 'Accueil', :controller=>'index', :action=>'accueil' %></li>
                          <li role="presentation" class="active" > <%= link_to 'Photos', :controller=>'index', :action=>'photos' %></li>
                          <li role="presentation"> <%= link_to 'M ecrire', :controller=>'index', :action=>'contact' %></li>
                          </ul>
            </div>

            <div class="col-md-4">
              <%= render "shared/reseaux_sociaux_haut" %>                
            </div>

     </div>
</div>


      <div class="row">

           <div class="col-md-8"  >                      
               <%=render "index/photos_contenu" %>                     
           </div>
            
           <div class="col-md-4"  >  
               <%=render "shared/menu_fixe_droit" %>
          </div>     

      </div>


    

</div>


  <%=render "shared/footer" %>

app/views/index/show_messages.html.erb
<div class=container>

 <div id="barremenu">

      <div class="row">
            <div class="col-md-8">
                           <ul class="nav nav-pills nav-justified ">
                         <li role="presentation"> <%= link_to 'Accueil', :controller=>'index', :action=>'accueil' %></li>
                          <li role="presentation"  > <%= link_to 'Photos', :controller=>'index', :action=>'photos' %></li>
                          <li role="presentation" class="active"> <%= link_to "M'écrire", :controller=>'index', :action=>'contact' %></li>
                          </ul>
            </div>

            <div class="col-md-4">
              <%= render "shared/reseaux_sociaux_haut" %>                
            </div>

     </div>
</div>


      <div class="row">

           <div class="col-md-8"  >  
           
           <h1> il y a <%=@message.count%> membre dans la base</h1>
               <%  @message.each do |f|  %>  
                   <p></p>
                   ---------------------------
                   <p> <%= f.prenom %>   <%=link_to "Modifier", :controller=>'index', :action=>'modifier_messages', :id=>f.id%> <%=link_to "Effacer", :controller=>'index', :action=>'effacer_messages', :id=>f.id%>   </p>
                   <p> <%= f.nom %></p>
                   <p> <%= f.message %></p>
                   <p> <%= f.mail %></p>
                   
               
               <% end %>
           </div>
            
           <div class="col-md-4"  >  
               <%=render "shared/menu_fixe_droit" %>
          </div>     

      </div>


    

</div>


  <%=render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Projetc</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">
  
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/shared/_footer.html.erb
 <div id="footer">
              <div class="panel-footer">
                    <a href="https://www.youtube.com/watch?v=eGrW0u0C_FIhttps://www.youtube.com/watch?v=eGrW0u0C_FI" target="_blank"> <i class="fa fa-youtube-square" aria-hidden="true"></i>YouTube</a>
                    <a href="https://www.facebook.com/people/Cl%C3%A9mence-de-Villeneuve/519459672" target="_blank"><i class="fa fa-facebook-square" aria-hidden="true"></i>Facebook</a>
                    <a href="https://www.instagram.com/clemencedevilleneuve/" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i>Instagram</a>

            </div>
        </div>

app/views/shared/_menu_fixe_droit.html.erb
<div id="menu_fixe_droite">
          <div id="bloc_menu_fixe_droite">

            <div class="row" >

                <div id="menu_dates" >

                    <h1>Prochaines dates</h1>
                      <ul class="spectacles">

                        <li><h2>Au Boui-boui à Lyon </h2></li>
                        <li><a href="http://www.billetreduc.com/166853/evt.htm" target="_blank">19h du mardi au samedi jusqu'au 31 décembre 2016 (Réserver ici)</a></li>
                        <li><h2>Au festival Top in Humour</h2></li>
                        <li><a href="http://www.topinhumour.fr/finale-des-tremplins-2016/" target="_blank">le 27 novembre 2016 (Réserver ici)</a></li>
                        <li><h2>Au Boui-boui à Lyon </h2></li>
                        <li><a href="http://www.billetreduc.com/166853/evt.htm" target="_blank">Le week end en 2017 (Réserver ici)</a></li>
                        
                          <%  @prochaines_dates.each do |f|  %>
                          
                           <li><h2><%= f.nom %>  </h2></li>
                           <li><a href=<%= f.date_texte %>  target="_blank"><%= f.lien %>  (Réserver ici)</a></li>
                          
                          <% end %>

                      </ul>

                </div>



            </div>

            <div class="row">


                  <div id="menu_facebook">
                      <h1>Facebook</h1>

                        <iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2FPage-Cl%C3%A9mence-de-Villeneuve-1555509148086811%2F&tabs=timeline&width=300&height=1000&small_header=true&adapt_container_width=true&hide_cover=false&show_facepile=true&appId=1699272216991241" width="300" height="1000" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe> 

                   </div>

            </div>

              </div>
</div>

app/views/shared/_reseaux_sociaux_haut.html.erb
<div id="reseaux_sociaux_haut">

              <a href="https://www.youtube.com/watch?v=eGrW0u0C_FIhttps://www.youtube.com/watch?v=eGrW0u0C_FI" target="_blank"> <i class="fa fa-youtube-square" aria-hidden="true"></i></a>
            <a href="https://www.facebook.com/people/Cl%C3%A9mence-de-Villeneuve/519459672" target="_blank"><i class="fa fa-facebook-square" aria-hidden="true"></i></a>
            <a href="https://www.instagram.com/clemencedevilleneuve/" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a>
</div>